prompt.go: Adopt io.ReadCloser and io.WriteCloser
As mentioned in #46, there is an error when I run `go get github.com/manifoldco/promptui`:

```
github.com/manifoldco/promptui/prompt.go:88:11: cannot use p.stdin (type io.Reader) as type io.ReadCloser in assignment:
io.Reader does not implement io.ReadCloser (missing Close method)
```

This commit simply fixes it(fixes #46). But I'm not sure this will cause side-effects since I haven't read other codes yet.